from app.database import Base
from app.models.attendance import (
    AttendanceClockRecord,
    AttendanceException,
    AttendanceProcessLog,
    AttendanceResult,
    AttendanceSchedule,
    ClockRecord,
    EmployeeAttendanceDetail,
    ShiftSwap,
    ShiftAttendanceConfirmation,
)
from app.models.assistant import AiBriefingEvent, AiContextPack, AiConversation, AiMessage, AiWatchlistItem
from app.models.assistant_usage import AssistantUsage
from app.models.agent_communication import (
    AgentChannelBinding,
    AgentEvent,
    AgentOperationApproval,
    AgentOutboxMessage,
    AgentProfile,
    AgentRateLimit,
    AgentRun,
    ChatInboxMessage,
    CommunicationChannel,
    DingTalkInboundReceipt,
    ExternalMessageLog,
    MultimodalEvidence,
)
from app.models.executive import (
    AluminumPriceDaily,
    CostDailyResult,
    CostMonthlyReviewStatus,
    CostMonthlyRollup,
    CostPriceMaster,
    CostVarianceRecord,
    CostWorkshopStrategy,
    MachineDailyCostSnapshot,
    MachineDailyProfitSnapshot,
    ProcessingFeeRule,
    ProcessingFeeSurcharge,
)
from app.models.imports import FieldMappingTemplate, ImportBatch, ImportRow
from app.models.master import Employee, Equipment, MasterCodeAlias, MesTerminalBinding, Position, Team, Workshop, WorkshopTemplateConfig
from app.models.energy import (
    EnergyImportRecord,
    IotEnergySnapshot,
    IotEnergySyncRun,
    MachineEnergyDailyCompare,
    MachineEnergyRecord,
)
from app.models.consumable import DailyConsumableLog
from app.models.mes import (
    CoilFlowEvent,
    MesCoilSnapshot,
    MesImportRecord,
    MesMachineLineSnapshot,
    MesMaterialRecord,
    MesReferenceItem,
    MesStockRecord,
    MesSyncCursor,
    MesSyncRunLog,
    MesWipTotalSnapshot,
    MesWorkshopProcessRecord,
    MesYieldRecord,
)
from app.models.production import (
    AlloySpecBreakdown,
    FieldAmendment,
    MobileReminderRecord,
    MobileShiftReport,
    OverhaulDaily,
    ProductionException,
    ProductionPlanDaily,
    RecoveryDaily,
    ShiftProductionData,
    ShipmentOutflowRecord,
    WorkOrder,
    WorkOrderEntry,
)
from app.models.quality import DataQualityIssue, QualityIssueLog, QualityYieldDaily
from app.models.rag import (
    HermesApprovedLesson,
    HermesLearningEvent,
    HermesProfessionalKnowledgeEntry,
    HermesShortTermMemory,
    RagChunk,
    RagDocument,
    RagEmbedding,
    RagQueryLog,
    RagSourceIngestion,
)
from app.models.hermes_factory_brain import (
    HermesCodexConstructionRun,
    HermesDingTalkSamplingRule,
    HermesKnowledgeUnit,
    HermesLongTermRule,
    HermesSoulProfile,
)
from app.models.hermes_data_audit import HermesCorrectionAction, HermesDataAuditRun
from app.models.reconciliation import DataReconciliationItem, MappingReconciliationRun
from app.models.reports import (
    DailyFactBundleRun,
    DailyFactBundleSnapshot,
    DailyFactCorrection,
    DailyReport,
    DailyReportHistoryRecord,
    OperationPeriodSnapshot,
)
from app.models.rule_config import RuleConfig
from app.models.shift import ShiftConfig
from app.models.system import AuditLog, SystemConfig, User

__all__ = [
    'Base',
    'User',
    'SystemConfig',
    'AuditLog',
    'Workshop',
    'Team',
    'Position',
    'Employee',
    'Equipment',
    'MesTerminalBinding',
    'WorkshopTemplateConfig',
    'MasterCodeAlias',
    'ShiftConfig',
    'AttendanceSchedule',
    'ClockRecord',
    'AttendanceClockRecord',
    'ShiftSwap',
    'AttendanceResult',
    'AttendanceException',
    'AttendanceProcessLog',
    'ShiftAttendanceConfirmation',
    'AiConversation',
    'AiMessage',
    'AiContextPack',
    'AiBriefingEvent',
    'AiWatchlistItem',
    'AssistantUsage',
    'AgentProfile',
    'CommunicationChannel',
    'AgentChannelBinding',
    'AgentEvent',
    'AgentOutboxMessage',
    'ChatInboxMessage',
    'DingTalkInboundReceipt',
    'AgentRun',
    'ExternalMessageLog',
    'MultimodalEvidence',
    'AgentOperationApproval',
    'AgentRateLimit',
    'EmployeeAttendanceDetail',
    'ShiftProductionData',
    'MobileShiftReport',
    'MobileReminderRecord',
    'ProductionException',
    'WorkOrder',
    'WorkOrderEntry',
    'FieldAmendment',
    'EnergyImportRecord',
    'IotEnergySnapshot',
    'IotEnergySyncRun',
    'MachineEnergyRecord',
    'MachineEnergyDailyCompare',
    'DailyConsumableLog',
    'MesImportRecord',
    'MesCoilSnapshot',
    'MesMachineLineSnapshot',
    'MesWorkshopProcessRecord',
    'MesStockRecord',
    'MesMaterialRecord',
    'MesYieldRecord',
    'MesReferenceItem',
    'MesWipTotalSnapshot',
    'CoilFlowEvent',
    'MesSyncCursor',
    'MesSyncRunLog',
    'DataQualityIssue',
    'QualityYieldDaily',
    'QualityIssueLog',
    'RagDocument',
    'RagChunk',
    'RagQueryLog',
    'RagEmbedding',
    'RagSourceIngestion',
    'HermesLearningEvent',
    'HermesShortTermMemory',
    'HermesApprovedLesson',
    'HermesProfessionalKnowledgeEntry',
    'HermesSoulProfile',
    'HermesLongTermRule',
    'HermesDingTalkSamplingRule',
    'HermesKnowledgeUnit',
    'HermesCodexConstructionRun',
    'HermesDataAuditRun',
    'HermesCorrectionAction',
    'ProductionPlanDaily',
    'AlloySpecBreakdown',
    'ShipmentOutflowRecord',
    'RecoveryDaily',
    'OverhaulDaily',
    'DataReconciliationItem',
    'MappingReconciliationRun',
    'ImportBatch',
    'ImportRow',
    'FieldMappingTemplate',
    'DailyFactBundleRun',
    'DailyFactBundleSnapshot',
    'DailyFactCorrection',
    'DailyReport',
    'DailyReportHistoryRecord',
    'OperationPeriodSnapshot',
    'RuleConfig',
    'AluminumPriceDaily',
    'CostPriceMaster',
    'CostWorkshopStrategy',
    'CostDailyResult',
    'CostMonthlyReviewStatus',
    'CostMonthlyRollup',
    'CostVarianceRecord',
    'ProcessingFeeRule',
    'ProcessingFeeSurcharge',
    'MachineDailyCostSnapshot',
    'MachineDailyProfitSnapshot',
]
