from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any, Sequence


BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from app.domain import daily_report_field_contract as contract_module


REPO_ROOT = BACKEND_ROOT.parent
DEFAULT_OUTPUT_PATH = REPO_ROOT / "docs" / "hermes" / "daily-report-field-contract.md"
GENERATED_NOTICE = "<!-- Generated by backend/scripts/render_daily_report_field_contract.py; do not edit by hand. -->"


def build_contract_payload() -> dict[str, Any]:
    normative_fields = contract_module.normative_daily_report_fields()
    template_fields = [
        field_name
        for group_fields in contract_module.FIELD_GROUPS.values()
        for field_name in group_fields
    ]
    fields = []
    for field_name in normative_fields:
        contract = contract_module.daily_report_field_contract_for(field_name)
        fields.append(
            {
                "field_name": contract.field_name,
                "group": contract.group,
                "unit": contract.unit,
                "business_time_scope": contract.business_time_scope,
                "business_time_start": contract_module.BUSINESS_TIME_STARTS[contract.business_time_scope],
                "tolerance": contract.tolerance,
                "reference_role": contract.reference_role,
            }
        )
    source_order = list(contract_module.FACT_SOURCE_LANE_ORDER)
    return {
        "contract_version": contract_module.DAILY_REPORT_FIELD_CONTRACT_VERSION,
        "normative_field_count": len(normative_fields),
        "template_field_count": len(template_fields),
        "template_only_fields": [
            {"field_name": field_name, "reason": reason}
            for field_name, reason in contract_module.TEMPLATE_ONLY_FIELD_REASONS.items()
        ],
        "business_time_starts": dict(contract_module.BUSINESS_TIME_STARTS),
        "owner_daily_submission_time": contract_module.OWNER_DAILY_SUBMISSION_TIME,
        "owner_daily_late_time": contract_module.OWNER_DAILY_LATE_TIME,
        "source_order": source_order,
        "source_priorities": {
            source_lane: contract_module.source_lane_priority(source_lane)
            for source_lane in source_order
        },
        "output_skill_reference_priority": contract_module.source_lane_priority(
            contract_module.SOURCE_LANE_OUTPUT_SKILL_REFERENCE
        ),
        "maximum_tolerance": max(contract.tolerance for contract in contract_module.DAILY_REPORT_FIELD_CONTRACTS.values()),
        "fields": fields,
    }


def render_contract_markdown(payload: dict[str, Any] | None = None) -> str:
    data = payload or build_contract_payload()
    lines = [
        GENERATED_NOTICE,
        "# 鑫泰铝业日报 127 字段合同",
        "",
        f"> 合同版本：`{data['contract_version']}`。`D:\\输出skill` 仅作为 compare-only 答案钥匙，不能作为事实源填数。",
        "> RAG 只用于解释和检索，不能生成实时数字，也不能覆盖钉钉、授权纠正、MES/WMS 或扫码补录事实。",
        "",
        "## 门禁摘要",
        "",
        f"- 规范字段：`{data['normative_field_count']}`",
        f"- 模板展示字段：`{data['template_field_count']}`",
        f"- 单字段最大允许误差：`{_display_number(data['maximum_tolerance'])}`",
        f"- 常规生产业务日开始：`{data['business_time_starts'][contract_module.BUSINESS_TIME_STANDARD]}`",
        f"- 坯料相关业务日开始：`{data['business_time_starts'][contract_module.BUSINESS_TIME_BILLET]}`",
        f"- owner 日报提交时间：`{data['owner_daily_submission_time']}`",
        f"- 迟报判定时间：`{data['owner_daily_late_time']}`",
        "- 未在答案钥匙出现的规范字段必须通过同名 `.na.json` 明确声明；否则门禁为 `blocked`。",
        "",
        "## 事实来源顺序",
        "",
        "| 顺序 | 来源通道 | 分值 |",
        "|---:|---|---:|",
    ]
    for index, source_lane in enumerate(data["source_order"], start=1):
        lines.append(f"| {index} | `{_cell(source_lane)}` | {data['source_priorities'][source_lane]} |")
    lines.extend(
        [
            "",
            f"`output_skill_reference` 分值为 `{data['output_skill_reference_priority']}`，不属于事实来源顺序。",
            "",
            "## 127 个规范字段",
            "",
            "| # | 字段 | 分组 | 单位 | 业务时间 | 允许误差 | 答案钥匙角色 |",
            "|---:|---|---|---|---|---:|---|",
        ]
    )
    for index, field in enumerate(data["fields"], start=1):
        lines.append(
            "| {index} | `{field_name}` | `{group}` | {unit} | `{scope}` ({start}) | {tolerance} | `{role}` |".format(
                index=index,
                field_name=_cell(field["field_name"]),
                group=_cell(field["group"]),
                unit=_cell(field["unit"]),
                scope=_cell(field["business_time_scope"]),
                start=_cell(field["business_time_start"]),
                tolerance=_display_number(field["tolerance"]),
                role=_cell(field["reference_role"]),
            )
        )
    lines.extend(
        [
            "",
            "## 仅模板展示字段",
            "",
            "以下字段保留在 130 字段展示模板中，但不进入 127 字段规范分母。",
            "",
            "| 字段 | 原因 |",
            "|---|---|",
        ]
    )
    for item in data["template_only_fields"]:
        lines.append(f"| `{_cell(item['field_name'])}` | `{_cell(item['reason'])}` |")
    return "\n".join(lines).rstrip() + "\n"


def write_contract_document(output_path: Path = DEFAULT_OUTPUT_PATH) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_contract_markdown(), encoding="utf-8")
    return output_path


def contract_document_is_current(output_path: Path = DEFAULT_OUTPUT_PATH) -> bool:
    if not output_path.is_file():
        return False
    return output_path.read_text(encoding="utf-8") == render_contract_markdown()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Render the canonical 127-field daily report contract.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    parser.add_argument("--check", action="store_true", help="Exit non-zero when the committed document is stale.")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.check:
        if contract_document_is_current(args.output):
            print(f"current {args.output}")
            return 0
        print(f"stale {args.output}")
        return 1
    path = write_contract_document(args.output)
    print(f"wrote {path}")
    return 0


def _display_number(value: Any) -> str:
    numeric = float(value)
    return str(int(numeric)) if numeric.is_integer() else str(numeric)


def _cell(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


if __name__ == "__main__":
    raise SystemExit(main())
