"""
阈值配置。
集中定义自动校验使用的阈值，替代旧流程中人工凭经验判断的环节。
"""

from __future__ import annotations

DEFAULT_THRESHOLDS: dict[str, float | int] = {
    'MIN_ATTENDANCE': 1,
    'MAX_ATTENDANCE': 50,
    'MIN_WEIGHT': 0.0,
    'MAX_SINGLE_SHIFT_WEIGHT': 500.0,
    'MIN_ENERGY': 0.0,
    'MAX_ELECTRICITY_DAILY': 100000.0,
    'MAX_GAS_DAILY': 50000.0,
    'RECONCILIATION_TOLERANCE_PERCENT': 5.0,
}

# 考勤
MIN_ATTENDANCE = DEFAULT_THRESHOLDS['MIN_ATTENDANCE']
MAX_ATTENDANCE = DEFAULT_THRESHOLDS['MAX_ATTENDANCE']

# 重量（吨）
MIN_WEIGHT = DEFAULT_THRESHOLDS['MIN_WEIGHT']
MAX_SINGLE_SHIFT_WEIGHT = DEFAULT_THRESHOLDS['MAX_SINGLE_SHIFT_WEIGHT']

# 能耗
MIN_ENERGY = DEFAULT_THRESHOLDS['MIN_ENERGY']
MAX_ELECTRICITY_DAILY = DEFAULT_THRESHOLDS['MAX_ELECTRICITY_DAILY']
MAX_GAS_DAILY = DEFAULT_THRESHOLDS['MAX_GAS_DAILY']

# 差异核对
RECONCILIATION_TOLERANCE_PERCENT = DEFAULT_THRESHOLDS['RECONCILIATION_TOLERANCE_PERCENT']
