from app.routers import assistant, assistant_actions, attendance, auth, command, dashboard, dingtalk, energy, imports, master, mes, mobile, ocr, production, quality, realtime, reconciliation, reports, rule_configs, team_lead, templates, users, work_orders

__all__ = [
    'assistant',
    'assistant_actions',
    'attendance',
    'auth',
    'command',
    'dashboard',
    'dingtalk',
    'energy',
    'imports',
    'master',
    'mes',
    'mobile',
    'ocr',
    'production',
    'reconciliation',
    'reports',
    'rule_configs',
    'team_lead',
    'templates',
    'users',
    'quality',
    'realtime',
    'work_orders',
]
