from __future__ import annotations

AUTO_CONFIRMED_REPORT_STATUS = 'auto_confirmed'
APPROVED_REPORT_STATUS = 'approved'
SUBMITTED_REPORT_STATUS = 'submitted'
RETURNED_REPORT_STATUS = 'returned'
UNREPORTED_STATUS = 'unreported'

CANONICAL_REPORT_SCOPE = AUTO_CONFIRMED_REPORT_STATUS

AUTO_CONFIRMED_REPORT_STATUSES = {APPROVED_REPORT_STATUS, AUTO_CONFIRMED_REPORT_STATUS}
READY_REPORT_STATUSES = {SUBMITTED_REPORT_STATUS, *AUTO_CONFIRMED_REPORT_STATUSES}

